DROP TABLE IF EXISTS Objects;
CREATE TABLE IF NOT EXISTS Objects (
  object_creation_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  object_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  object_title VARCHAR(50) NOT NULL,
  object_description VARCHAR(1000)
);
